-- this should also happen on another thread
-- which makes life a liiiittle more difficult

ClientManager = class{
	init = function(self, server, port, channel)

		-- this ID should be generated by something else and stored in a file
		-- it will match the know the identifier of the player this controls
		self.id = Identity()

		self.connected = false
		--self:connect()

	end,

	update = function(self, dt)

		local connected = self.connected
		if connected then
			local channels = self.channels
			local inbound = channels.inbound

			local pending = inbound:getCount()
			for i = 1, pending do
				local message = inbound:pop()

				-- give this message to the turn manager
				local action = tonumber(message.message)
				if action then

					-- this should be given to the turn manager
					print(action)
					getManager().objects[action]:toggle()


				end

				-- send this message to the correct player model?
				-- for now, use this to activate the node with this key!

			end

			-- get stuff from client
			-- send stuff to client
		end

	end,


	broadcast = function(self, message)

		-- this should come from the turn manager

		-- how do i make the actions this action manager handles completely arbitrary?
		-- nodes and tiles need a specific id
		-- when units are created they need a specific id

		local connected = self.connected
		if connected then

			-- package message for transmission
			-- what might a message be, an arbitrary table?
			
			



			local channels = self.channels
			local outbound = channels.outbound
			outbound:push(message)
			
		end

	end,

	connect = function(self)

		local connected = self.connected

		if not connected then

			local id = self.id:get()

			-- the thread running the client
			local client = love.thread.newThread('threads/thread.lua')

			-- channel for pushing info to the thread
			local dispatch = love.thread.getChannel('dispatch')

			-- channel for broadcasting commands to other users
			local outbound = love.thread.getChannel('outbound')

			-- channel for recieving updates from other users
			local inbound = love.thread.getChannel('inbound')


			-- todo: include uid and maybe something secret
			local connection = {
				server = 'node.kneeko.com',
				port = 1337,
				channel = 'ping-channel',
				id = id,
			}
			
			dispatch:push(connection)
			client:start()

			local channels = {
				dispatch = dispatch,
				outbound = outbound,
				inbound = inbound,
			}

			self.client = client
			self.channels = channels
			self.connected = true

		end

	end,

	disconnect = function(self)

		local connected = self.connected
		if connected then

			local channels = self.channels
			local dispatch = channels.dispatch
			dispatch:push({action = 'stop'})
			self.connected = false

		end

	end,

	keypressed = function(self, key, code)
		if key == 'q' then
			self:disconnect()
		end

		if key == 'r' then
			self:connect()
		end
	end,
		


}

--[[

make a noobhub wrapper which uses a seperate thread?

]]--